# Generated by Django 2.1.2 on 2019-02-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronic', '0002_auto_20190212_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
