# Generated by Django 2.1.2 on 2019-02-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronic', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
