# Generated by Django 2.1.3 on 2018-11-02 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='exam_at',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='school.Course'),
        ),
    ]
