# Generated by Django 2.1.3 on 2018-11-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_grade_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
